server:
  port: 8000
  address: 0.0.0.0
#  servlet:
#    encoding:
#      force-response: true
#      charset: UTF-8
spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/database_name
    username: db_id
    password: db_pw

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: false

    properties:
      hibernate:
        format-sql: true

  application:
    name: KPSC-DLPC

  devtools:
    restart:
      enabled: true

admin:
  username: admin_id
  password: admin_pw

jwt:
  jwtkey: your_jwt_key

domain:
  domain: your_domain